version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: fiber_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fiber_db
    ports:
      - "5432:5432"